#!/usr/bin/env ruby
require 'optparse'
require "activity_generator"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: activity_generator [options]"

  opts.on('-f', '--file=FILE_PATH', String, "Path to YAML file containing pre-populated sequence of activity to generate") do |f|
    options[:file] = f
  end

  opts.on('-l', '--log-path=LOG_PATH', String, "Path to write log file of activity") do |log_path|
    options[:log_path] = log_path
  end

  opts.on("-h", "--help", "Prints the help") do
    puts opts
    exit
  end
end.parse!

if options[:file].present?
  puts "Running through the sequence populated from #{options[:file]}..."
else
  puts "Dropping into interactive prompt for custom sequence input... (input `exit` to quit)"
end

ActivityGenerator::Runner.new(options)
